### ISSUE TITLE
Blacklist shitty spirits

### ISSUE THREAD

**Issue by cbyington** [cbyington/whisky-sentry#1]
Thinking about excluding rum and vodka from triggering text alerts here.

I personally enjoy tequila, mescal, and gin -- so I'm OK to continue receiving alerts on rare bottles of those spirits.

Objections @spacemanzack ?

**Comment by spacemanzack** [comment]
@cbyington 👍

**Comment by cbyington** [comment]
This change is made & deployed :shipit:
