### ISSUE TITLE
Adding Beer

### ISSUE THREAD

**Issue by spacemanzack** [cbyington/whisky-sentry#2]
I'd like to receive alerts on rare bottles of beer. If it's low level of effort, I'd like to request adding beer to the alerting list, with the same logic you're using for spirits 😄

**Comment by cbyington** [comment]
At first blush this seems to fit into the existing framework -- I'll look into implementing this the next time I have a work session on this project, likely within a few weeks.

Are there other keywords I should add that are specific to beer?  I assume "single barrel," etc. won't be relevant, which would leave us with the allocation trigger only.

**Comment by cbyington** [comment]
@spacemanzack whisky sentry is now updated to alert on beer!

Currently, a beer will trigger an alert if any of the following conditions is true and it isn't sold out:
- product name includes the string `'limit'` (as in `bottle limit`)
- allocation <= 3

Are there beer names we should search for as well?  E.g. for whisky products, sentry looks for `'Larue'`, `'Stagg'`, etc.

**Comment by cbyington** [comment]
@spacemanzack ideas on terms to add here (special beers to look out for)?

**Comment by spacemanzack** [comment]
@cbyington for sure! `Brouwerij Drie Fonteinen`, `Brasserie Cantillon`, `Bottle Logic`, `Modern Times`

**Comment by cbyington** [comment]
@spacemanzack these beer names are in production now, :woop: !

**Comment by spacemanzack** [comment]
💥
